### ISSUE TITLE
zipcode redundant

### ISSUE THREAD

**Issue by kvlahromei** [open311/swagger-open311#17]
the field request.zipcode is explicitly defined but informal also mentioned at the request.adress field:

> This should be provided from most specific to most general geographic unit, eg address number or cross streets, street name, neighborhood/district, city/town/village, county, **postal code** .

Makes it sense to remove this additional field or do we want to add more structured adress fields?

**Comment by philipashlock** [comment]
For the existing v2 spec we should acknowledge that it's redundant, but I've added an issue to the spec issue tracker to see if we can address this in the next version of the spec - https://github.com/open311/open311.github.io/issues/48
